### ISSUE TITLE
Updating rez.mat

### ISSUE THREAD

**Issue by hkneu-95** [MouseLand/Kilosort2#125]
After visualising results in phy2 and making changes (identifying noisy channels etc) is there a way for rez.mat to incorporate these changes as I wish to use the results in MATLAB for further analysis?

**Comment by nsteinme** [comment]
You can load the outputs of phy into matlab directly, using (
https://github.com/kwikteam/npy-matlab) for npy files and matlab's
"readtable" (for example) for the tsv files. It's better if you can do that
rather than putting the results back into rez.mat. Does it work for your
purpose or can you explain in more detail?

**Comment by hkneu-95** [comment]
Thanks Nick! I think that should work.
