### ISSUE TITLE
GUI error when updating number channels to be plotted

### ISSUE THREAD

**Issue by angelonc** [MouseLand/Kilosort2#13]
I found when using a small number of channels that the scroll options in the GUI error when you include all the channels in traceview. To fix this, I added the following after line 1255:

`                       if nCh>numel(cm.chanMap)
                            nCh = numel(cm.chanMap);
                        end`

**Comment by nsteinme** [comment]
Great, thanks - mind making a pull request with the fix?

**Comment by angelonc** [comment]
Done; I actually found a better way to do it, the fix I posted above will get stuck when you reach nChannels, but I included the better fix in the pull request.

Cheers to you guys for creating such an awesome tool. The GUI makes it so easy to assess KiloSort2's performance and tweak parameters!

**Comment by marius10p** [comment]
@angelonc, one thing you cannot really assess from the GUI is the splitting performance at the very end, which happens after the template subtraction step. Kilosort2 actually runs the main optimization biased towards overmerging, because the splits at the end are pretty good and we found this strategy works better than the other way around (bias the main optimization towards oversplitting). 

 @nsteinme we should say somewhere that you cannot see the effects of splits and merges in the GUI. In particular, you cannot really see the effect of changing AUCsplit.

**Comment by angelonc** [comment]
Right, thanks for the reminder! I suppose the biggest issue I was having with Kilosort1 was inconsistency in spike detection, and the GUI makes it really easy to visualize where spikes are being missed and the effects of spike detection parameters.
