### ISSUE TITLE
Oversplit data

### ISSUE THREAD

**Issue by hkneu-95** [MouseLand/Kilosort2#137]
Hi,
So I have been using Kilosort2 for 32 channel e-phys data. One observation is this certain oversplitting where what appears to be the same waveform is detected with respect to different reference points and therefore shows largely different amplitudes and is often restricted to small sections of the recording. Also they seem to have spikes in complementary sections of the recording. I have noticed this in several instances and have attached one example below. We have been manually merging them in Phy but would like to know what might be the reason and if such instances could be reduced by parameter changes.
![Capture2](https://user-images.githubusercontent.com/56253702/68605014-f71ccd00-04ab-11ea-96cb-a058c87f8eab.PNG)
![Capture](https://user-images.githubusercontent.com/56253702/68605021-fc7a1780-04ab-11ea-9724-3a9478eb835a.PNG)

**Comment by marius10p** [comment]
I think this is because of how the spikes are aligned to either the negative or positive waveform extremes. We don't want to force negative peaks only, because certain kinds of spikes would not be detected well by that. 

Until we come up with better alignment, your best option is to write a custom matching step, detecting best timelags between waveforms and merging those that are too similar.
