### ISSUE TITLE
Error using gpuArray/eig - Input matrix contains NaN or Inf

### ISSUE THREAD

**Issue by njmiska** [MouseLand/Kilosort2#142]
Hi, I've encountered this issue twice now while trying to run neuropixel data through Kilosort2 (see image below).  Appears to be happening on the last batches.  This is being done as part of the international brain lab data pipeline.  Ran it by @oliche and he said he hasn't seen it before and that it might be a bug.  Also appears to be similar to this currently open issue: https://github.com/MouseLand/Kilosort2/issues/45.  Any ideas what might be causing this?

![Image from iOS (1)](https://user-images.githubusercontent.com/48487164/69074308-00b3b100-0a27-11ea-8f2c-4f4954d0402f.jpg)

**Comment by marius10p** [comment]
That other issue is due to extremely many batches, which runs out the GPU memory. 

This one seems to have given NaNs or Infs somewhere in that matrix. You should enter debug mode just before that error and look at that matrix. We would need to know if its NaNs or Infs, and where they are in the matrix.
