### ISSUE TITLE
Un is not orthonormal

### ISSUE THREAD

**Issue by Addisonbc** [MouseLand/Kilosort2#168]
Hi, thank you for developing kilosort algorithm and keeping up with issues here! 
While I'm reading through your paper and looking at the output, a question came up:

The rez.UA is supposed to be the Un said in the paper, right? And its dimension should be `channels * clusters * (3) components * batches`. So, I took the Un of one cluster by referencing `rez.UA(:,iCluster,:,iBatch)`, and found that the column vectors are not of unit length. In fact, it's decreasing from 1st to 3rd component.

Then I took a look at the spatiotemporal components (multiply each column / rows of the U and W separately), and found that the first would constitute the major waveforms, while the other two would for a large part add up noises. I'm a bit confused. Does this mean that one spatiotemporal component is enough for spike-sorting? Or is there something I did wrong here?
![sptiotemporal components](https://user-images.githubusercontent.com/56739632/71768610-827f7100-2ee5-11ea-9ec4-24beef61e7e9.jpg)

**Comment by marius10p** [comment]
They are orthogonal, but not orthonormal because they were multiplied with the singular values. This is simply a convenience in the code to keep track of the low-rank factorization. 

This waveform appears to be mostly on one channel. In that case, by definition the SVD will be well approximated by a single spatiotemporal pattern: the wave over the one channel.

**Comment by Addisonbc** [comment]
Thank you very much for clearing things up! I was wondering about that cause the paper did not mention singular values.

It seems that for Plexon V-probes that's always the case, I think I'll reduce the number of components to 2, then.
