### ISSUE TITLE
Channel info for sorted spikes

### ISSUE THREAD

**Issue by ecoluo** [MouseLand/Kilosort2#174]
Hi, I checked the phy github, but I still haven't found the .npy file in which I can find each sorted spike belongs to which channel. So, I can't get the waveform of each spike in matlab if I need it.

**Comment by marius10p** [comment]
I believe its "templates_ind.npy" which tells you the channels for each template (in order of waveform amplitude). Sorted spikes do no get assigned to individual channels, because they get detected with the template summing information from many neighboring channels. So you'd have to look up the template number for each spike, and then find the first channel for that template.

**Comment by ecoluo** [comment]
> I believe its "templates_ind.npy" which tells you the channels for each template (in order of waveform amplitude). Sorted spikes do no get assigned to individual channels, because they get detected with the template summing information from many neighboring channels. So you'd have to look up the template number for each spike, and then find the first channel for that template.

Thank you so much! I think I've solved my question according to your advice.
