### ISSUE TITLE
Threshold used for detecting spikes in residuals

### ISSUE THREAD

**Issue by dimokaramanlis** [MouseLand/Kilosort2#184]
Hi Marius,

I would like to ask how are the spikes extracted from the residual during the main optimization of KS2. The wiki mentions a "common spike detector based on threshold crossings". Is the threshold used ops.spkTh or ops.Th(1)? It seems that only ops.Th(1) gets passed to the mexGetSpikes2 function.

**Comment by marius10p** [comment]
It's ops.Th(1). The rationale is that we're looking for spikes that have at least that much variance (square rooted), because that is also the threshold for keeping a template. Even though we expect the raw spikes to have noise variance too, it's a good way to make sure we test a lot of potential candidate spikes. 

ops.spkTh is used for the initial spike detection for drift tracking.

**Comment by dimokaramanlis** [comment]
Thanks!
