### ISSUE TITLE
Remaining artefact from electric stimulation

### ISSUE THREAD

**Issue by cnavntoft** [MouseLand/Kilosort2#202]
Hello,
I record activity in response to electric stimulation (a cochlear implant) using a multi-channel probe in the midbrain of a mouse. To remove the stimulation artefact, we have implemented an artefact removal step (blanking) in Kilosort2 before the the spike sorting step. It works well for single pulses but not perfectly for a fast pulse train with multiple pulses after each other. In the following manual correction in Phy2, we see remaining artefacts. The remaining artefact is much larger than the spikes. However, will this bias the template towards the remaining artefact and not a spike shape so that less spikes are detected? 
If so, would it be possible to force Kilosort2 to build the template on data where the stimulation artefact is nicely removed and then apply this template to the pulse train data?
Or do you have other ideas to how Kilosort can ignore the large remaining artefacts (maybe we can set a maximum amplitude for what should be considered as a spike)?
In advance, thank you for your help.

**Comment by yagui** [comment]
Hi,
I'm having a similar problem. I have movement artifacts that usually are not a big problem, because even with artifacts kilosort is able to find good units.
But for some dataset it seems that this artifacts greatly bias the kilosort algorithm and it prevents kilosort to find good units. In some cases this is a low percentage of spikes, but for some other cases is all artifact an almost no spikes.
This is an example of the latter case, all the cluster created from kilosort are highlighted in colors and in the raw signal you can see a lot of spikes that where not assigned to any cluster.
![phy_screenshot_20200505083322_TraceView](https://user-images.githubusercontent.com/4296015/81067032-110ff900-8eac-11ea-99e9-b6f815e7415e.png)
![phy_screenshot_20200505083301_TraceView](https://user-images.githubusercontent.com/4296015/81067037-12d9bc80-8eac-11ea-87b5-9d3951194c26.png)
![phy_screenshot_20200505083248_TraceView](https://user-images.githubusercontent.com/4296015/81067044-14a38000-8eac-11ea-88f0-703b72c7c70f.png)
This movement artifacts are ramdon so I don't have a know time to remove them.
I was also thinking to have a threshold and remove anything that goes above the threshold.
I was wondering if there is a particular set options that would help to ignore this artifact and make kilosort able to catch the good units.

**Comment by JoseGuzman** [comment]
I have a similar issue: did you try setting up `ops.criterionNoiseChannels` in your probe design?

https://github.com/MouseLand/Kilosort2/blob/48bf2b81d8ad3bece919f358e071520d5b0930e1/configFiles/createChannelMapFile.m#L39

**Comment by cnavntoft** [comment]
> I have a similar issue: did you try setting up `ops.criterionNoiseChannels` in your probe design?
> 
> https://github.com/MouseLand/Kilosort2/blob/48bf2b81d8ad3bece919f358e071520d5b0930e1/configFiles/createChannelMapFile.m#L39
