### ISSUE TITLE
Sorting data from distant electrodes

### ISSUE THREAD

**Issue by alexkaz2** [MouseLand/Kilosort2#21]
Thank you very much for the amazing tool!

We record from an array of widely spread 16 electrodes (rec. sites separated by ~0.5mm), s.t. we don't expect to detect a spike on more than one electrode, but we do have lots of highly correlated noise (behavior, electric artifacts, biology :\ ).

We have a hard time to optimize the hyper-parameters for our task:
- Should we disable the weighted whitening across channels? If so, what is the safe way to achieve it?
- What is the optimal way to format the array ('probe') layout? Just leave the 'Linear16x1'?
- Any other way to convey our constraints and assumptions?

I am fully aware that KiloSort was not designed for this task, but even with the default settings it succeeded to impress us!

Alex & Co.

**Comment by marius10p** [comment]
Hi Alex,

Don't worry about the whitening step: if the only correlated signal across electrodes is noise, then it will correctly whiten that noise, which will reduce its impact on each electrode. 

For the probe layout, 16x1 would be fine, but you'll have to increase the spacing between electrodes, so you might need to make a new channel map file anyway. 

In the first Kilosort we had a variable for each channel saying which group of channels it corresponds to: "kcoords". People with arrays such as yours would give each electrode a separate kcoords value. I will bring that back into Kilosort2, but it will take a few days before I can get to it.

**Comment by jbraun7** [comment]
Hi Marius,

I'm just jumping in on the kcoords. I saw it is possible to define it in both the GUI and the channelmap script, but when browsing through the code, I did not find a single location where kcoords is used. Is this me not finding where it is used or is it still waiting to be integrated?
Are you planning to integrate ops.criterionNoiseChannels similar to kilosort1 as well?

Cheers,
Jonas

**Comment by marius10p** [comment]
Sorry, kcoords has still not been implemented.

**Comment by Saudruch** [comment]
Hi Marius,
 I have related question. I am testing Kilosort2 for the first time and I want to set up parameters for 16 tetrode/64 channel probe also with wide separation of tetrodes (not expected detection of signal from one cell with more then 1 tetrode). Since the kcoords setting isn't implemented yet, I will separate my data by tetrode and process each tetrode separately.
I am just wondering what would be the correct channel map setting for a single tetrode, does it matter if I create linear 1x4 map or should I make it 2x2 map (which is the physical configuration of the tetrodes, except not on the vertical but horizontal 2x2 plane). I cannot read the code enough to understand how will this affect the clustering process.

 Thank you, Petr

**Comment by marius10p** [comment]
It is beneficial to sort all tetrodes together, because they share the same noise sources. If you see any contamination problems across tetrodes, then you can worry about the placement of the tetrodes. The distances only matter for sorting electrodes from nearest to furthest from each site.
