### ISSUE TITLE
gui (and possibly KS also) not working with single channel data

### ISSUE THREAD

**Issue by nsteinme** [MouseLand/Kilosort2#25]
Gui also fails when numchans<16

**Comment by nsteinme** [comment]
Also getting errors with a 4-channel dataset, not exactly sure what's the problem but I get a bunch of these, even after re-starting matlab (and, my GPU is not doing anything else like a display): 

Warning: An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_LAUNCH_FAILED 
> In learnAndSolve8b (line 3)
  In ksGUI/runSpikesort (line 782)
  In ksGUI/runAll (line 629)
  In ksGUI>@(~,~)obj.runAll() (line 319)

**Comment by adehad** [comment]
I can confirm we are also having issues with single channel data. 
We tried padding dummy channels (of 1s) to get 4 and 16 total channels as we did in KS1, but now KS2 determines that these are bad channels which likely leads to some errors. Hence we set: `` ops.minfr_goodchannels = 0; ``.
**System:**
NVIDIA GTX960M 2+6GB (dedicated+shared). MATLAB 2018b. Windows 10 180914-1434.

**Using VS2017:**
It seems that extractPCbatch2() is returning empty vectors.
```
Error using  - 
An unexpected error occurred during CUDA execution. The CUDA error was:
an illegal memory access was encountered

Error in learnAndSolve8b (line 142)
    [W, U, mu] = mexSVDsmall2(Params, dWU, W, iC-1, iW-1, Ka, Kb);

```
And trying again afterwards
```
Error using gpuArray.zeros
An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_ILLEGAL_ADDRESS
```

**Using VS2013:**
It seems that an error might be specific to the number of channels ( #22 ).
```
Warning: An unexpected error occurred during CUDA execution. 
The CUDA error was:
CUDA_ERROR_ILLEGAL_ADDRESS 
Conversion to logical from gpuArray is not possible.

Error in median (line 153)
        if isnan(x(nCompare))        % Check last index for NaN

Error in learnAndSolve8b (line 264)
            toc, ibatch, niter, Nfilt, sum(nsp), median(mu), numel(st0), ndrop)
```
I checked the `mu` here and it was a `1x1 gpuArray` - so I pased in `gather(mu)` instead of `mu`.
Doing this went well until the `ops.fig`  `imagesc()` plots, `gather()` did not help this time, so I disabled the plots.
During the next loop iterations, the console is spammed with warnings:
```
Warning: An unexpected error occurred during CUDA execution. 
The CUDA error was:
CUDA_ERROR_ILLEGAL_ADDRESS 
> In learnAndSolve8b (line 3)
		ops = rez.ops;
```
followed by an error:
```
Error using gpuArray.ones 
An unexpected error occurred trying to launch a kernel. 
The CUDA error was:
invalid configuration argument

Error in learnAndSolve8b (line 107)
        pm = pm = pmi(ibatch) * gpuArray.ones(Nfilt, 1, 'double');
```

As you noted, once an error occured, MATLAB needed to then be restarted before any more GPU functions can be performed, otherwise simple errors like initialising an array throw an error:
```
Error using gpuArray.zeros
An unexpected error occurred during CUDA execution. 
The CUDA error was:
an illegal memory access was encountered

Error in extractTemplatesfromSnippets (line 17)
dd = gpuArray.zeros(ops.nt0, 5e4, 'single');
```

**Comment by jvoigts** [comment]
Have the same issue here when trying to sort 4 channels at a time. Haven't had the time to do any real reading on it, but it looks like there's a few hard coded magic numbers in learnAndSolve8b that assume large channel counts.

**Comment by alejoe91** [comment]
Hi, I also found problems in sorting tetrodes.
I'm able to run kilosort2 using 32 channels and the kcoords parameter, but if I split the recording and run each tetrode separately I get the same error.

**Comment by boydmeredith** [comment]
I'm having this issue as well when trying to cut clusters from a single tetrode. Any idea what is causing this?

**Comment by marius10p** [comment]
I think @jenniferColonell fixed the tetrode problem in the Kilosort code. I don't know if there are GUI problems left for tetrode data @nsteinme ?

**Comment by nsteinme** [comment]
@boydmeredith could you try again with latest code, and if you have a problem, please describe exactly what error you get?

**Comment by warnerwarner** [comment]
Was this ever fixed? I'm still getting errors if use channels < 16

**Comment by boydmeredith** [comment]
@warnerwarner @nsteinme it's working for me with the new code!
