### ISSUE TITLE
is it possible to continute using previous templates on new binary file

### ISSUE THREAD

**Issue by babaq** [MouseLand/Kilosort2#37]
it is pretty common to do several tests and therefore result in several test binary files under one electrodes position, so if we want to consistently sorting spikes into corresponding cluster under the fixed electrodes position when relatively small or slow drifts may occur, we would concatenated the binary files in timely order, and do kilosort on this file.

I am wandering is it possible to use previously saved sorting results including channel templates to start with on new binary files, so that the template and clusters IDs could continually working on new binary files provided they all come from the same electrodes at a fixed position.

I guess it's just the templates from the first batch is not needed, but instead use the ones in previous results and treat the new first batch as the second batch as if the templates already been detected.

**Comment by marius10p** [comment]
This would require significant extra development, and is not a high priority right now, sorry. It might be better anyway to sort all files together, because KS2 goes through data starting at the middle of the reordered binary file, so not in temporal order, which helps to keep track of units because it matches together all time points that have similar drift location, regardless of time.

**Comment by babaq** [comment]
I understand there are more urgent features to consider, just sometimes we have to concat several binary files together which is quite big and probably will get bigger if some chronic implant recording will do.
the ability to continuously sorting file by file could speed up data pipeline, especially when KiloSort results get better, so no `Phy` manual checking is necessary and then all could be automatic.

**Comment by marius10p** [comment]
This can be done now.
