### ISSUE TITLE
tetrode channel map

### ISSUE THREAD

**Issue by MarcelMB** [MouseLand/Kilosort2#51]
Hey,

I have a quick question concerning the channel map. I know that the kcoords variable is an easy way to define which channel belongs to one bundle of electrodes. In case of 4 tetrodes
kcoords=[1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4];

However I am wondering if the xcoords and ycoords have any meaning during the sporting process if the kcoords variable is defined. 
Basically you can assume that the depth (ychoords is the same for one tetrode, 4 channels) and that the xchoords is a random value for different tetrodes (depeding on how far away they are from each other)? But do this two values matter if we define kchoords?

Thank your for creating Kilosort2!

**Comment by marius10p** [comment]
Hi, actually kcoords has not been implemented yet, but you can achieve similar behavior by giving xcoords and ycoords that are far enough from each other: it won't use channels that are far away from the template max. We will eventually add kcoords, but I recommend you set xcoords and ycoords anyway because it makes it easier to visualize in the Phy GUI. For example, you could set the xs of one tetrode as 1, 2,3 ,4, and the ys far from each other 1000, 2000, 3000, 4000, etc

**Comment by MarcelMB** [comment]
Thank you! 

But do you actually mean to separate tetrodes by the ys (e.g. for 4 tetrodes like this): 
ycoords   = [1000 1000 1000 1000 2000 2000 2000 2000 2000 3000 3000 3000 3000 4000 4000 4000 4000]';
and
xcoords   = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16];

Which basically makes kilosort look only in the channels where ychoords are e.g. =1000?

**Comment by marius10p** [comment]
Yes, but for aesthetic reasons in phy I would recommend xcoords to be 1234123412341234...

**Comment by MarcelMB** [comment]
thanks for the fast response
