### ISSUE TITLE
Having Trouble getting started

### ISSUE THREAD

**Issue by meyert11** [MouseLand/Kilosort2#74]
Hey guys,

I went through the Neuropixels course (so I have some rudimentary Kilosort experimence). I've been trying to setup a Kilosort Rig from our Convolutional Neural Network Rig. Here are my versions:

After trial and error, I got this to 'work': Matlab 2016a &  all needed toolboxes, Visual studio 2012 C++ compiler, CUDA 7.5. 

I can run mexGPUall, and mex completes successfully. I acquired example data from: http://data.cortexlab.net/singlePhase3/data/ 
- specifically rawDataSample.bin

*The problem*
I open Kilosort, load the selected data file, slect the working and results director. When I get to the channel mapping, regardless of what I select (Phase3A, 3B1, 3B2) there is a matlab error during 'Computing whitening filter...' 

The error is: 
'Error using -
Matrix dimensions must agree.

Error in ksFilter (line 24)
dataRAW = dataRAW - mean(dataRAW, 1);
'
There are more error lines going up the tree to where the callback in the gui it errored, let me know if that'd be helpful. Needless to say, the Run box never ungrays out. Any suggestions?

Travis

**Comment by nsteinme** [comment]
Unfortunately this is caused by a change in matlab that happened in 2016b
-
https://blogs.mathworks.com/loren/2016/10/24/matlab-arithmetic-expands-in-r2016b/

There is not much you can do: you could replace that particular line with
the bsxfun equivalent but there are many more instances and there is no way
to search to find them all (I have tried this...). Essentially, KS2 is not
compatible with matlab prior to 2016b. Sorry :/

**Comment by meyert11** [comment]
Thanks Nick! It's actually a relief to know it wasn't something I had done :) I'll give a new matlab a try, hopefully it'll be compatible with my combination of CUDA and compilers!
