### ISSUE TITLE
Isolating Sorted Spikes?

### ISSUE THREAD

**Issue by aproca** [MouseLand/Kilosort2#77]
How I would go about isolating individual sorted spikes of the real data (including its waveform, unit, and channel), rather than the templates or the average spikes. Is this in a specific .npy file(s)?

Thanks!

**Comment by djoshea** [comment]
In general, you can use the spike times to extract a slice of time samples from the raw `imec.ap.bin` file. There is code to this provided in both:
- The [cortex-lab/spikes repo](https://github.com/cortex-lab/spikes) and described [here](https://github.com/cortex-lab/neuropixels/wiki/Other_analysis_methods#loading-raw-waveforms-or-spike-triggered-lfp-eg)
- My own [djoshea/neuropixel-utils repo](https://github.com/djoshea/neuropixel-utils) and explained in a [walk-through here](https://djoshea.github.io/neuropixel-utils/waveforms/#extracting-waveforms-via-kilosortdataset)

My code is a bit more involved to learn since it aims to be a one-stop shop wrapper around Kilosorted datasets, but it has the additional nice feature of "cleaning" up the waveforms by removing the spikes from other neurons that occurred in the same time window. Hope this helps!

**Comment by jsiegle** [comment]
Python code that serves the same purpose is available here:

https://github.com/AllenInstitute/ecephys_spike_sorting/tree/master/ecephys_spike_sorting/modules/mean_waveforms

**Comment by aproca** [comment]
Thank you so much for the helpful responses! In the meantime, I was using this code for kilosort2: https://github.com/cortex-lab/KiloSort/issues/35#issuecomment-268874720 . I was using the rez2 file because it contains rez.st3. What data is in each column of st3 exactly, and what is the difference between st2 and st3? I'm confused as to whether the provided code is correct in assigning the fifth column to spikeClusters.

**Comment by djoshea** [comment]
Awesome @jsiegle, I didn't know about this. Thanks!

@aproca, the `.st2` field has the same format as `.st3`, and they start out being the same. st2 is a snapshot of the spikes right after the initial sorting in [learnAndSolve8b.m](https://github.com/MouseLand/Kilosort2/blob/2a399268d6e1710f482aed5924ba90d52718452a/mainLoop/learnAndSolve8b.m), and st3 is subsequently modified by split, merge, and threshold cutoff operations.

Each row is a spike, and the columns are documented [here](https://github.com/MouseLand/Kilosort2/wiki/7.-Output-variables). I'm not exactly sure what the fourth column is; it's similar to the amplitude in column 3 (Matlab-style indices starting at 1) but slightly lower valued. They are set in mexMPnu8.cu on lines 317 and 319. @marius10p would know, it maybe has something to do with the height of nearby peaks?

**Comment by marius10p** [comment]
Only the first three columns are informative. The fourth and fifth column are for debugging purposes, for now, and will probably be excluded soon.
